CREATE TABLE ESCOLA(
	id_escola INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_municipio INT REFERENCES MUNICIPIO(id_municipio),
	nome_escola VARCHAR(100) NOT NULL,
	cod_escola INTEGER UNIQUE NOT NULL,
	rede VARCHAR(100) NOT NULL
);
