CREATE TABLE IES(
	id_ies INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	id_municipio INT REFERENCES MUNICIPIO(id_municipio),
	nome_ies VARCHAR(100) NOT NULL,
	sigla_ies VARCHAR(20),
	codigo_ies INT UNIQUE NOT NULL,
	rede VARCHAR(100) NOT NULL
);
